package com.minivision.aop.face.thrift;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-24")
public class FaceInfo implements org.apache.thrift.TBase<FaceInfo, FaceInfo._Fields>, java.io.Serializable, Cloneable, Comparable<FaceInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FaceInfo");

  private static final org.apache.thrift.protocol.TField FACE_FEATURES_FIELD_DESC = new org.apache.thrift.protocol.TField("faceFeatures", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FaceInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FaceInfoTupleSchemeFactory();

  public java.util.List<FaceFeatures> faceFeatures; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FACE_FEATURES((short)1, "faceFeatures");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FACE_FEATURES
          return FACE_FEATURES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FACE_FEATURES, new org.apache.thrift.meta_data.FieldMetaData("faceFeatures", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FaceFeatures.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FaceInfo.class, metaDataMap);
  }

  public FaceInfo() {
  }

  public FaceInfo(
    java.util.List<FaceFeatures> faceFeatures)
  {
    this();
    this.faceFeatures = faceFeatures;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FaceInfo(FaceInfo other) {
    if (other.isSetFaceFeatures()) {
      java.util.List<FaceFeatures> __this__faceFeatures = new java.util.ArrayList<FaceFeatures>(other.faceFeatures.size());
      for (FaceFeatures other_element : other.faceFeatures) {
        __this__faceFeatures.add(new FaceFeatures(other_element));
      }
      this.faceFeatures = __this__faceFeatures;
    }
  }

  public FaceInfo deepCopy() {
    return new FaceInfo(this);
  }

  @Override
  public void clear() {
    this.faceFeatures = null;
  }

  public int getFaceFeaturesSize() {
    return (this.faceFeatures == null) ? 0 : this.faceFeatures.size();
  }

  public java.util.Iterator<FaceFeatures> getFaceFeaturesIterator() {
    return (this.faceFeatures == null) ? null : this.faceFeatures.iterator();
  }

  public void addToFaceFeatures(FaceFeatures elem) {
    if (this.faceFeatures == null) {
      this.faceFeatures = new java.util.ArrayList<FaceFeatures>();
    }
    this.faceFeatures.add(elem);
  }

  public java.util.List<FaceFeatures> getFaceFeatures() {
    return this.faceFeatures;
  }

  public FaceInfo setFaceFeatures(java.util.List<FaceFeatures> faceFeatures) {
    this.faceFeatures = faceFeatures;
    return this;
  }

  public void unsetFaceFeatures() {
    this.faceFeatures = null;
  }

  /** Returns true if field faceFeatures is set (has been assigned a value) and false otherwise */
  public boolean isSetFaceFeatures() {
    return this.faceFeatures != null;
  }

  public void setFaceFeaturesIsSet(boolean value) {
    if (!value) {
      this.faceFeatures = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case FACE_FEATURES:
      if (value == null) {
        unsetFaceFeatures();
      } else {
        setFaceFeatures((java.util.List<FaceFeatures>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case FACE_FEATURES:
      return getFaceFeatures();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case FACE_FEATURES:
      return isSetFaceFeatures();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof FaceInfo)
      return this.equals((FaceInfo)that);
    return false;
  }

  public boolean equals(FaceInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_faceFeatures = true && this.isSetFaceFeatures();
    boolean that_present_faceFeatures = true && that.isSetFaceFeatures();
    if (this_present_faceFeatures || that_present_faceFeatures) {
      if (!(this_present_faceFeatures && that_present_faceFeatures))
        return false;
      if (!this.faceFeatures.equals(that.faceFeatures))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetFaceFeatures()) ? 131071 : 524287);
    if (isSetFaceFeatures())
      hashCode = hashCode * 8191 + faceFeatures.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(FaceInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetFaceFeatures()).compareTo(other.isSetFaceFeatures());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFaceFeatures()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.faceFeatures, other.faceFeatures);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FaceInfo(");
    boolean first = true;

    sb.append("faceFeatures:");
    if (this.faceFeatures == null) {
      sb.append("null");
    } else {
      sb.append(this.faceFeatures);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FaceInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FaceInfoStandardScheme getScheme() {
      return new FaceInfoStandardScheme();
    }
  }

  private static class FaceInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<FaceInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FACE_FEATURES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.faceFeatures = new java.util.ArrayList<FaceFeatures>(_list8.size);
                FaceFeatures _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new FaceFeatures();
                  _elem9.read(iprot);
                  struct.faceFeatures.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setFaceFeaturesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FaceInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.faceFeatures != null) {
        oprot.writeFieldBegin(FACE_FEATURES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.faceFeatures.size()));
          for (FaceFeatures _iter11 : struct.faceFeatures)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FaceInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FaceInfoTupleScheme getScheme() {
      return new FaceInfoTupleScheme();
    }
  }

  private static class FaceInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<FaceInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFaceFeatures()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetFaceFeatures()) {
        {
          oprot.writeI32(struct.faceFeatures.size());
          for (FaceFeatures _iter12 : struct.faceFeatures)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.faceFeatures = new java.util.ArrayList<FaceFeatures>(_list13.size);
          FaceFeatures _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new FaceFeatures();
            _elem14.read(iprot);
            struct.faceFeatures.add(_elem14);
          }
        }
        struct.setFaceFeaturesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

